"""empty message

Revision ID: 419e213d692e
Revises: e0b9a9c94ddd
Create Date: 2022-11-23 18:26:53.475337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419e213d692e'
down_revision = 'e0b9a9c94ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
